#!/usr/bin/env bash
# Bash script that displays information about subdomains

finder () {
	dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk -v sd="$2" 'BEGIN { FS = " " } ; { print " The subdomain " sd " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
	finder "$1" "www"
	finder "$1" "lb-01"
	finder "$1" "web-01"
	finder "$1" "web-02"

elif [ "$#" == 2 ]
then
	finder "$1" "$2"
fi
