#!/usr/bin/env bash
# Redirect to another page

sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.html

REDIRECT=\
"server {
        listen 80;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=IotUxgPqbik permanent;
        }
}"

bash -c "echo -e '$REDIRECT' > /etc/nginx/sites-available/default"
sudo service nginx restart
