#!/usr/bin/env bash
# Redirect to another page

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

REDIRECT=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=IotUxgPqbik permanent;
        }
}"

bash -c "echo -e '$REDIRECT' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ]
then
        sudo service nginx start
else
        sudo service nginx restart
fi
