#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page

sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

ERROR_PAGE=\
"server {
        listen 80;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=IotUxgPqbik permanent;
        }
        error_page 404 /404.html
        location /404.html {
                internal;
        }
}"

bash -c "echo -e '$ERROR_PAGE' > /etc/nginx/sites-available/default"
sudo service nginx start
