#!/usr/bin/env bash
# Install and configures HAProxy on lb-01 server

sudo apt update
sudo apt -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt install -y haproxy=2.7.\*
sudo service haproxy start

CONFIGURATION=\
"
frontend myfrontend
        bind *:80
        mode http
        default_backend myservers

backend myservers
        balance roundrobin
        server 75516-web-01 54.146.93.137:80 check
        server 75516-web-02 18.209.224.64:80 check
"

bash -c "echo -e '$CONFIGURATION' >> /etc/haproxy/haproxy.cfg"

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
