#!/usr/bin/env bash
# Bash script that generates MySQL dump and creates a compressed archive out of it
sudo mysqldump -u root -p='$2' tyrell_corp > backup.sql
tar -czvf $(date +"%d-%m-%Y").tar.gz backup.sql
