#!/usr/bin/env bash
# Bash script that displays content of the current directory
# In a list format where part of name after dash is displayed

for content in *
do
	echo "$content" | cut -d '-' -f2
done
