#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

cp /etc/hosts /etc/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" /etc/hosts.new
echo "8.8.8.8 facebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
