#!/usr/bin/env bash
# Bash script that runs Nginx as nginx user
chmod 644 /etc/nginx/nginx.conf 
chown -R nginx /etc/nginx/nginx.conf
sed -i 's/user www-data;/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache
sudo -u nginx service nginx restart
