#!/usr/bin/env bash
# Bash script that runs Nginx as nginx user in 7 lines or less
chmod 644 /etc/nginx/nginx.conf 
chown -R nginx /etc/nginx/nginx.conf
sed -i 's/user www-data;/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 0.0.0.0:8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
